version: "3"
services:
  web:
    container_name: tienda-pamys-spring
    build: .
    ports:
      - 8090:8080
    links:
      - mysql
    volumes:
      - .:/usr/src/app
  mysql:
    container_name: tienda-pamys-mysql
    image: mysql:8.0.13
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: DB_PAMYS
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
